langage: php
php:
    - '7.4'
node:
    - '12.16'

install:
    - make install

cache:
    directories:
        - ./vendor
        - ./node_modules

script:
    - make lint
    - php bin/console lint:yaml /config
    - php bin/console lint:twig /templates
